apiVersion: apps/v1
kind: replicaSet
metadata:
  name: rc-pod
  label: replicaPod
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: nginx-app
  template:
    metadata:
      name: nginx-pod
      label:
        app: nginx-app
    spec:
      containers:
        name: nginx-container
        image: nginx
        Ports:
          containerPort: 80


/*

selector:
  matchExpressions:
    {key: app, operator: In, values: [frontend,backend ]}

*/