apiVersion: apps/v1
kind: deployment
metadata:
  name: nginx-deploy
  label:
    app: nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      name: nginx-pod
      label:
        app: nginx-app
    spec:
      container:
        name: nginx-container
        image: nginx
        ports:
          containerPort: 80
