apiVersion: v1
kind: pod
metadata:
  name: pv-pod
spec:
  containers:
    name: test-container
    image: nginx
    volumeMounts:
      mountPath: /test-pd
      name: test-volume
  volume:
    name: test-volume
    persistentVolumeClaim:
      claimName: my-disk-claim3

/*
by default reclaim policy is delete.

*/