apiVersion: v1
kind: pod
metadata:
  name: test-pod
spec:
  containers:
    name: test-container
    image: nginx
    volumeMounts:
      name: cache-volume
      mountPath: /cache
  volume:
    name: cache-volume
    emptyDir: {}
  