apiVersion: v1
kind: pod
metadata:
  name: redis-hostPath
spec:
  containers:
    name: redis-container
    image: redis
    volumeMounts:
      mountPath: /test-mnt
      name: test-vol
  volumes:
    name: test-vol
    hostPath:
      path: ./test-vol