apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
type: opaque
data:
  username: encodedValue
  password: encodedValue

/*
encrypt it using:-
echo -n "data" | base64
echo -n "data" | base64

  */