apiVersion: v1
kind: Pod
metadata:
  name: busyBox
spec:
  containers:
    image: busybox
    name: busybox
    command: "/bin/bash"
    args: "-c","sleep 600"
    env:
      name: myusername
      valuefrom:
        secretKeyRef:
          name: secet-demo
          key: username.txt