apiVersion: v1
kind: pod
metadata:
  name: BusyBox
spec:
  volume:
    name: secret-volume
    secret:
      secretName: secret-demo
  containers:
    name: BusyBox
    image: BusyBox
    mountVolumes:
      name: secret-volume
      mountPath: /mydata